[package]
name = "radio_pi"
version = "0.1.0"
authors = ["Andrew Burgess <andrew@andrewburgess.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
